In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
OLD_PATH = "./data/oldData/"
PROC_PATH = "./data/processedData/"
PATH ="./data/"

In [3]:
os.listdir(PROC_PATH)

['empty.txt', 'used_cars_processed.csv', 'vehicles_processed.csv']

In [4]:
pd.read_csv(PROC_PATH + "used_cars_processed.csv", nrows=1).columns

Index(['ID', 'pricesold', 'yearsold', 'zipcode', 'Mileage', 'Make', 'Model',
       'Year', 'Trim', 'Engine', 'BodyType', 'NumCylinders', 'DriveType',
       'datesold'],
      dtype='object')

In [11]:
df_ucars = pd.read_csv(PROC_PATH + "used_cars_processed.csv")
df_ucars.head()
df_ucars.info()
df_ucars.isna().sum()[df_ucars.isna().sum()>0]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122142 entries, 0 to 122141
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            122142 non-null  int64
 1   pricesold     122142 non-null  int64
 2   yearsold      122142 non-null  int64
 3   zipcode       121233 non-null  object
 4   Mileage       122142 non-null  int64
 5   Make          122142 non-null  object
 6   Model         121569 non-null  object
 7   Year          122142 non-null  float64
 8   Trim          73219 non-null   object
 9   Engine        95044 non-null   object
 10  BodyType      101356 non-null  object
 11  NumCylinders  122142 non-null  int64
 12  DriveType     97292 non-null   object
 13  datesold      122142 non-null  object
dtypes: float64(1), int64(5), object(8)
memory usage: 13.0+ MB

zipcode        909
Model          573
Trim         48923
Engine       27098
BodyType     20786
DriveType    24850
dtype: int64

In [14]:
df_ucars.Engine.value_counts()

350                                                       2085
V8                                                        1894
V6                                                         929
5.0                                                        612
5.7                                                        590
                                                          ...
4.7 Liter Magnum V8                                          1
1.6 L/6 Valves                                               1
5.9 liter 360 V8                                             1
1.8L 1798CC 110Cu. In. l4 GAS DOHC Naturally Aspirated       1
M52TU 2.8L                                                   1
Name: Engine, Length: 22399, dtype: int64

In [21]:
#make everything lower case 
df_ucars['Engine'] = df_ucars['Engine'].str.lower()
df_ucars.Engine.value_counts()

v8                               2221
350                              2085
v6                               1108
5.0                               612
5.7                               590
                                 ...
5.5l v8 f dohc 32v twin turbo       1
327.0 8 cylinder                    1
3.4 3l na v6 double overhead        1
353 hc                              1
m52tu 2.8l                          1
Name: Engine, Length: 19892, dtype: int64

##### We got more matches

In [35]:
#if number of cylinders is in the engine name than put it on NumCylinders

# Filter rows where NumCylinders is 0 and Engine contains v8...
mask = (df_ucars['NumCylinders'] == 0) & (df_ucars['Engine'].str.contains('v8|v7|v6|v5|v4|v3|v2|v1|i8|i7|i6|i5|i4|i3|i2|i1'))

# Set NumCylinders based on Engine
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v8|i8'), 'NumCylinders'] = 8
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v7|i7'), 'NumCylinders'] = 7
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v6|i6'), 'NumCylinders'] = 6
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v5|i5'), 'NumCylinders'] = 5
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v4|i4'), 'NumCylinders'] = 4
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v3|i3'), 'NumCylinders'] = 3
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v2|i2'), 'NumCylinders'] = 2
df_ucars.loc[mask & df_ucars['Engine'].str.contains('v1|i1'), 'NumCylinders'] = 1
#pd.set_option('display.max_rows', 20) #show more rows
df_ucars.head(20)

,ID,pricesold,yearsold,zipcode,Mileage,Make,Model,Year,Trim,Engine,BodyType,NumCylinders,DriveType,datesold
0,137178,7500,2020,786**,84430,Ford,Mustang,1988.0,LX,5.0l gas v8,Sedan,8,RWD,2020-11-23
1,96705,15000,2019,81006,0,Replica/Kit Makes,Jaguar Beck Lister,1958.0,NaN,383 fuel injected,Convertible,8,RWD,2019-09-30
2,119660,8750,2020,33449,55000,Jaguar,XJS,1995.0,2+2 Cabriolet,4.0l in-line 6 cylinder,Convertible,6,RWD,2020-12-23
3,80773,11600,2019,07852,97200,Ford,Mustang,1968.0,Stock,289 cu. in. v8,Coupe,8,RWD,2019-06-30
4,64287,44000,2019,07728,40703,Porsche,911,2002.0,Turbo X-50,3.6l,Coupe,6,AWD,2019-09-25
5,132695,950,2020,462**,71300,Mercury,Montclair,1965.0,NaN,no engine,Sedan,0,RWD,2020-04-17
6,132829,950,2020,105**,71300,Mercury,Montclair,1965.0,NaN,NaN,Sedan,0,NaN,2020-07-26
7,5250,70000,2019,07627,6500,Land Rover,Defender,1997.0,NaN,4.0 liter fuel injected v8,NaN,8,4WD,2019-09-12
8,29023,1330,2019,07043,167000,Honda,Civic,2001.0,EX,NaN,Coupe,4,FWD,2019-09-18
9,80293,25200,2019,33759,15000,Pontiac,GTO,1970.0,NaN,NaN,NaN,0,NaN,2019-10-16
10,158271,20000,2020,333**,51674,Jeep,Wrangler,2015.0,SPORT,3.6l flexible v6,SUV,6,4WD,2020-08-28
11,72418,14100,2019,07014,109500,Jeep,Wrangler,2012.0,Unlimited,3.6l,SUV,6,4WD,2019-05-11
12,91661,5700,2020,76051,1000000,Ford,F-100,1949.0,NaN,NaN,Standard Cab Pickup,8,RWD,2020-08-06
13,119358,6000,2020,384**,101501,Toyota,Prius,2009.0,NaN,1.5l electric and gas hybrid i4,4 door/hatchback,4,FWD,2020-11-15
14,131969,4000,2020,027**,118513,Toyota,Celica,1985.0,NaN,2.8l gas i6,Hatchback,6,RWD,2020-09-17
15,84062,3820,2019,V1W 5L6,377000,Jeep,Wrangler,1997.0,NaN,4.0,NaN,6,AWD,2019-04-25
16,144540,3330,2020,856**,47692,Buick,LeSabre,2004.0,CUSTOM,3.8l gas v6,Sedan,6,FWD,2020-05-22
17,142951,650,2020,628**,99999,Austin,NaN,1970.0,NaN,NaN,NaN,0,NaN,2020-08-06
18,142336,1480,2020,601**,166000,Nissan,Altima,2006.0,NaN,NaN,Sedan,6,NaN,2020-11-02
19,59728,18550,2019,60448,6714,Chevrolet,Camaro,2002.0,"Z28,SS,SLP",5.7 liter v8,Coupe,8,RWD,2019-11-24

In [39]:
#show number of missing values again
df_ucars.isna().sum()

ID                  0
pricesold           0
yearsold            0
zipcode           909
Mileage             0
Make                0
Model             573
Year                0
Trim            48923
Engine          27098
BodyType        20786
NumCylinders        0
DriveType       24850
datesold            0
dtype: int64

##### wowww no more missing values. let's wrap it up

In [41]:
df_ucars.to_csv(PATH + "/processedData/used_cars_processed.csv", index=False)